harnessApiVersion: '1.0'
type: PROMETHEUS
prometheusUrl: http://34.82.218.196:8080
usageRestrictions:
  appEnvRestrictions:
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - PROD
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - NON_PROD
